services:
  postgres:
    image: postgres:16
    container_name: nestjs_auth_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_auth_db
    ports:
      - '5433:5432'
    volumes:
      - nestjs_auth_db:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d nestjs_auth_db']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  nestjs_auth_db:
